FROM ubuntu:jammy-20220531
RUN apt update
RUN apt install -y gcc g++ gfortran libopenblas-dev liblapack-dev liblapacke-dev cmake git ccache rsync curl bash graphviz doxygen autotools-dev automake pkg-config
RUN apt install -y mpich
